###########
# site.title, site.url, site.author.name

title:   "Junsikahn's Blog"
title_separator: "-"
author:
  name: "Junsikahn"
description: "Junsikahn's Blog"

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
url: "https://junsikahn.github.io"
baseurl: ""

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false
